/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class indi_aljet_testjni_JNIUtil */

#ifndef _Included_indi_aljet_testjni_JNIUtil
#define _Included_indi_aljet_testjni_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     indi_aljet_testjni_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL Java_indi_aljet_testjni_JNIUtil_getWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
